const { withDangerousMod, withGradleProperties } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function getNodePath() {
  try {
    if (process.env.NODE_BINARY) {
      return process.env.NODE_BINARY;
    }
    
    const nodePath = execSync('which node', { encoding: 'utf8' }).trim();
    if (nodePath) {
      return nodePath;
    }
  } catch (e) {
    const homeDir = process.env.HOME || process.env.USERPROFILE;
    const nvmDir = path.join(homeDir, '.nvm', 'versions', 'node');
    
    if (fs.existsSync(nvmDir)) {
      const versions = fs.readdirSync(nvmDir).sort().reverse();
      if (versions.length > 0) {
        return path.join(nvmDir, versions[0], 'bin', 'node');
      }
    }
  }
  
  return 'node';
}

module.exports = function withNodePath(config) {
  config = withGradleProperties(config, (config) => {
    const nodePath = getNodePath();
    config.modResults.push({
      type: 'property',
      key: 'NODE_BINARY',
      value: nodePath,
    });
    return config;
  });

  config = withDangerousMod(config, [
    'android',
    (config) => {
      const settingsGradlePath = path.join(
        config.modRequest.platformProjectRoot,
        'settings.gradle'
      );

      try {
        if (fs.existsSync(settingsGradlePath)) {
          let content = fs.readFileSync(settingsGradlePath, 'utf8');
          
          if (!content.includes('NODE_BINARY setup')) {
            const nodePath = getNodePath();
            
            const nodeSetup = `  // NODE_BINARY setup - auto-generated by withNodePath plugin
  def nodeBinary = System.getenv("NODE_BINARY") ?: "${nodePath.replace(/\\/g, '\\\\')}"
  System.setProperty("NODE_BINARY", nodeBinary)
  
`;

            content = content.replace(
              /pluginManagement\s*\{/,
              `pluginManagement {\n${nodeSetup}`
            );
            
            content = content.replace(
              /commandLine\s*\(\s*"node"/g,
              'commandLine(nodeBinary'
            );

            fs.writeFileSync(settingsGradlePath, content, 'utf8');
            console.log('✅ Updated settings.gradle with NODE_BINARY path:', nodePath);
          }
        }
      } catch (e) {
        console.warn(`⚠️  Could not update settings.gradle: ${e.message}`);
      }

      return config;
    },
  ]);

  config = withDangerousMod(config, [
    'android',
    (config) => {
      const appBuildGradlePath = path.join(
        config.modRequest.platformProjectRoot,
        'app',
        'build.gradle'
      );

      try {
        if (fs.existsSync(appBuildGradlePath)) {
          let content = fs.readFileSync(appBuildGradlePath, 'utf8');

          if (!content.includes('AUTOLINKING TASK ORDER FIX')) {
            const taskOrderFix = `

// AUTOLINKING TASK ORDER FIX - auto-generated by withNodePath plugin
afterEvaluate {
    def packageListTask = tasks.findByName("generateAutolinkingPackageList")
    def newArchTask = tasks.findByName("generateAutolinkingNewArchitectureFiles")
    if (packageListTask != null && newArchTask != null) {
        newArchTask.dependsOn(packageListTask)
    }
}
`;
            content += taskOrderFix;
            fs.writeFileSync(appBuildGradlePath, content, 'utf8');
            console.log('✅ Added autolinking task-order fix to app/build.gradle');
          }
        }
      } catch (e) {
        console.warn(`⚠️  Could not update app/build.gradle: ${e.message}`);
      }

      return config;
    },
  ]);

  return config;
};